// ====================================================================
// LUẬN GIẢI.JS — Dữ liệu & hàm diễn giải DÙNG CHUNG cho 3 tab:
//   Nội Khí / Phi Tinh (phi-tinh.js) · Tìm Nhà (tim-nha.js) · Cửu Cung Lưới (cuu-cung-luoi.js)
//
// PHẢI load file này TRƯỚC 3 file trên trong index.html: cả 3 đã có sẵn pattern
// `window.X || {fallback riêng}` chờ đúng các window.* khai báo ở đây. Nếu load sau,
// mỗi file sẽ lặng lẽ dùng lại fallback riêng của nó — vẫn chạy đúng, nhưng quay về
// đúng tình trạng trùng lặp/dễ lệch mà file này sinh ra để giải quyết.
//
// LƯU Ý KỸ THUẬT: phải gán tường minh window.X = ... (không dùng const/let trần) —
// vì const/let ở top-level 1 file KHÔNG tự trở thành window.X cho file khác đọc,
// chỉ có var và function declaration mới tự động làm vậy.
// ====================================================================

// ===== 1. BẢNG NGŨ HÀNH GỐC =====
window.HANH_CUA_SAO  = {1:"Thủy",2:"Thổ",3:"Mộc",4:"Mộc",5:"Thổ",6:"Kim",7:"Kim",8:"Thổ",9:"Hỏa"};
window.HANH_SINH     = {"Mộc":"Hỏa","Hỏa":"Thổ","Thổ":"Kim","Kim":"Thủy","Thủy":"Mộc"};
window.HANH_KHAC     = {"Mộc":"Thổ","Thổ":"Thủy","Thủy":"Hỏa","Hỏa":"Kim","Kim":"Mộc"};
window.HANH_CUA_CUNG = {"Khảm":"Thủy","Khôn":"Thổ","Chấn":"Mộc","Tốn":"Mộc","Trung":"Thổ","Càn":"Kim","Đoài":"Kim","Cấn":"Thổ","Ly":"Hỏa"};

// ===== 2. SAO_Y_NGHIA — NGUỒN CHUẨN DUY NHẤT cho ý nghĩa Cửu Tinh =====
// Nội dung lấy NGUYÊN VĂN từ CUU_TINH_DATA (cuu-cung-luoi.js) — Ka đã xác nhận chọn bản này
// làm chuẩn (chi tiết hơn bản SAO_Y_NGHIA cũ từng có riêng trong phi-tinh.js).
// cat/hung là bản SAO Y NGUYÊN của khiSinhVuong/khiSuyTu (không diễn giải lại) để giữ đúng
// 1 nguồn sự thật — phi-tinh.js (yNghiaSaoTheoVan) dùng sy.cat/sy.hung mà không cần sửa logic.
window.SAO_Y_NGHIA = {
    1: { ten: "Nhất Bạch", tenKhac: "Tham Lang", tenDayDu: "Nhất Bạch (Tham Lang)", nguHanh: "Thủy", cung: "Khảm (+)",
        mauSac: "Trắng", bieuTuong: "Sông, biển, vùng bùn, khe núi sâu tối",
        coThe: "☵ Tai, Thận, Bàng quang, hệ thống sinh dục, tiết niệu, tuần hoàn máu, tủy xương và vùng thắt lưng",
        tinhChat: "Bồng bột, lãng đãng", loaiTinh: "Cát tinh",
        khiSinhVuong: "Vượng đinh lẫn tài, lợi cả văn lẫn võ, thi cử đỗ đạt, tiếng tăm lừng lẫy, sinh con trai thông minh, thăng quan phát tài. Cát tinh hàng đầu.",
        khiSuyTu: "Hoạ do tửu sắc, tan cửa nát nhà. Bệnh về tai, suy thận, bàng quang, sinh sản. Nặng thì hình khắc vợ, mù loà, yểu mệnh, sống phiêu bạt." },
    2: { ten: "Nhị Hắc", tenKhac: "Cự Môn", tenDayDu: "Nhị Hắc (Cự Môn)", nguHanh: "Thổ", cung: "Khôn (-)",
        mauSac: "Đen", bieuTuong: "Mộ phần, nơi hoang vu",
        coThe: "☷ Bụng, tỳ, cơ bắp và mô mềm",
        tinhChat: "Nhu mà tĩnh (mềm mỏng, bình tĩnh)", loaiTinh: "Hung tinh",
        khiSinhVuong: "Có quyền có của, cơ ngơi bề thế, vượng cả đinh lẫn tài. Thường xuất võ quý, phụ nữ cai quản gia đình, đa mưu.",
        khiSuyTu: "Tai hoạ vì sắc, dễ hoả hoạn, thị phi, hao tiền tốn của. Phụ nữ dễ xảy thai, đau bụng, mụn nhọt, bệnh ngoài da, ở goá, bệnh dai dẳng." },
    3: { ten: "Tam Bích", tenKhac: "Lộc Tồn", tenDayDu: "Tam Bích (Lộc Tồn)", nguHanh: "Mộc", cung: "Chấn (+)",
        mauSac: "Xanh lá cây", bieuTuong: "Rường, cột nhà, vườn góc, dụng cụ tra tấn",
        coThe: "☳ Chân, Gan, hệ thần kinh, gân mạch và các bệnh về hệ vận động",
        tinhChat: "Kình (mạnh mẽ) mà trực (thẳng thắn)", loaiTinh: "Hung tinh",
        khiSinhVuong: "Hưng gia lập nghiệp, giàu sang phú quý, công thành danh toại, vượng nhất ngành trưởng.",
        khiSuyTu: "Dễ dính kiện tụng, trộm cướp, bệnh tật, hình khắc vợ con. Bệnh nhiễm trùng máu, bệnh về chân, gan, mật." },
    4: { ten: "Tứ Lục", tenKhac: "Văn Xương", tenDayDu: "Tứ Lục (Văn Xương)", nguHanh: "Mộc", cung: "Tốn (-)",
        mauSac: "Xanh dương", bieuTuong: "Miếu, cây mây, dây thừng",
        coThe: "☴ Đùi, Đởm( túi mật), liên quan đến mạch máu, khí quản, các chứng phong thấp và trúng phong",
        tinhChat: "Hoà hoãn", loaiTinh: "Cát tinh",
        khiSinhVuong: "Thi cử đỗ đạt, quân tử thăng quan, tiểu nhân có tiền của, lấy được vợ hiền/chồng giỏi, có tài văn chương.",
        khiSuyTu: "Dễ mắc bệnh thần kinh, hen suyễn, sống phiêu bạt; đam mê tửu sắc phá tan cơ nghiệp. Dễ xảy thai, bệnh thắt lưng, tai nạn bất ngờ." },
    5: { ten: "Ngũ Hoàng", tenKhac: "Liêm Trinh", tenDayDu: "Ngũ Hoàng (Liêm Trinh)", nguHanh: "Thổ", cung: "Trung cung",
        mauSac: "Vàng", bieuTuong: "Đế quyền, rồng vàng, hoàng bào",
        coThe: "(Không có mô tả riêng)",
        tinhChat: "(Không có mô tả riêng)", loaiTinh: "Đại hung tinh",
        khiSinhVuong: "Khi ở đúng trung cung: vượng cả đinh lẫn tài, sự nghiệp phát triển.",
        khiSuyTu: "Khi bay ra hướng khác: Ngũ Hoàng đại sát, sát tinh lớn nhất. Gặp Thái Tuế/Tam Sát/Thất Sát thì hại người mất của, bệnh tật, nặng có thể nguy hiểm tính mạng." },
    6: { ten: "Lục Bạch", tenKhac: "Vũ Khúc", tenDayDu: "Lục Bạch (Vũ Khúc)", nguHanh: "Kim", cung: "Càn (+)",
        mauSac: "Trắng, bạc", bieuTuong: "Chuông, đỉnh (vạc), ngọc, đá, vàng",
        coThe: "☰ Đầu, Đại trường, xương khớp",
        tinhChat: "Cương mà động", loaiTinh: "Cát tinh",
        khiSinhVuong: "Lắm của đông người, quyền cao chức trọng, phát lớn về nghiệp võ, uy danh lừng lẫy. Cát tinh thứ ba.",
        khiSuyTu: "Dễ dính kiện tụng, vất vả chốn quan trường. Đau đầu, đau ngực, thương tích do kim loại. Hình hại vợ con, cô đơn." },
    7: { ten: "Thất Xích", tenKhac: "Phá Quân", tenDayDu: "Thất Xích (Phá Quân)", nguHanh: "Kim", cung: "Đoài (-)",
        mauSac: "Đỏ", bieuTuong: "Đao kiếm, kích, rìu",
        coThe: "☱ Miệng, Phổi, Liên quan đến hệ hô hấp (phế quản), miệng, lưỡi, họng và răng",
        tinhChat: "Quyết đoán mà nhanh nhẹn", loaiTinh: "Hung tinh",
        khiSinhVuong: "Vượng cả đinh lẫn tài, sự nghiệp phát đạt, chi út phát phúc, phát về nghiệp võ, quan vận hanh thông.",
        khiSuyTu: "Dễ gây rắc rối, sống lưu lạc, trộm cướp. Hoả hoạn, tổn thất nhân khẩu, bệnh hô hấp/phổi/cổ họng, bất lợi cho bé gái." },
    8: { ten: "Bát Bạch", tenKhac: "Tả Phù", tenDayDu: "Bát Bạch (Tả Phù)", nguHanh: "Thổ", cung: "Cấn (+)",
        mauSac: "Trắng", bieuTuong: "Vườn cây, gò đống",
        coThe: "☶ Tay, Vị, Tương ứng với các phần nhô ra trên cơ thể như mũi, vú, gót chân",
        tinhChat: "Bình an, dừng lại", loaiTinh: "Cát tinh",
        khiSinhVuong: "Công danh phú quý, hợp lập nghiệp/vượng tài, nghỉ ngơi dưỡng sức. Cát tinh thứ hai, có thể hoá giải hung sát.",
        khiSuyTu: "Dễ tổn hại trẻ nhỏ, bệnh liên quan tay chân, gân cốt, sống lưng, trướng bụng." },
    9: { ten: "Cửu Tử", tenKhac: "Hữu Bật", tenDayDu: "Cửu Tử (Hữu Bật)", nguHanh: "Hỏa", cung: "Ly (-)",
        mauSac: "Đỏ tía", bieuTuong: "Bếp lò, đèn, nến",
        coThe: "☲ Mắt, tim, vùng trung thượng vị (là phần bụng phía trên rốn và ngay dưới xương ức, chứa dạ dày, gan, tụy và tá tràng), ngực, vùng mặt và các chứng bệnh nhiệt, viêm nhiễm",
        tinhChat: "Nóng nảy hung bạo", loaiTinh: "Cát tinh",
        khiSinhVuong: "Phát phúc rất nhanh, vượng cả đinh lẫn tài, sự nghiệp ổn định, tài văn chương xuất chúng, phát phúc cho chi thứ.",
        khiSuyTu: "Tính tình kiên cường, khí khái, dễ bị hoả hoạn. Dễ thổ huyết, bệnh về tim và mạch máu, khó sinh." }
};
// Gán cat/hung = bản sao y nguyên khiSinhVuong/khiSuyTu (KHÔNG diễn giải lại) cho từng sao,
// để phi-tinh.js (yNghiaSaoTheoVan dùng sy.cat/sy.hung) tự động nhận đúng nội dung CUU_TINH_DATA.
Object.keys(window.SAO_Y_NGHIA).forEach(function(k) {
    let s = window.SAO_Y_NGHIA[k];
    s.cat = s.khiSinhVuong;
    s.hung = s.khiSuyTu;
});

// ===== 3a. QUAN HỆ NGŨ HÀNH SAO ↔ CUNG (thay cho qCungGoc trong phi-tinh.js và tnQuanHe
// trong tim-nha.js — cả 2 đã có hook window.xetQuanHeNguHanh, chỉ cần định nghĩa ở đây) =====
// Trả về CẢ dienGiai (tên field phi-tinh.js dùng) VÀ giai (tên field tim-nha.js dùng) — cùng nội dung.
// Giữ nguyên các nhãn loai ("tot"/"hao_tan"/"xau"/"che_nhe"/"binh") ĐÚNG như phi-tinh.js gốc,
// vì phi-tinh.js có so sánh trực tiếp .loai==="hao_tan" ở vài chỗ (không được đổi tên).
window.xetQuanHeNguHanh = function(hanhCung, sao) {
    let hs = window.HANH_CUA_SAO[sao];
    function ket(dienGiai, loai, nhan, diem) { return { dienGiai: dienGiai, giai: dienGiai, loai: loai, nhan: nhan, diem: diem }; }
    if (hanhCung === hs) return ket(`đồng hành (${hs})`, "binh", "Bình ổn", 0);
    if (window.HANH_SINH[hs] === hanhCung) return ket(`${hs} sinh ${hanhCung}`, "tot", "Sinh nhập — TỐT", 1);
    if (window.HANH_SINH[hanhCung] === hs) return ket(`${hanhCung} sinh ${hs}`, "hao_tan", "Hao tán — trung bình", 0);
    if (window.HANH_KHAC[hs] === hanhCung) return ket(`${hs} khắc ${hanhCung}`, "xau", "Khắc nhập — XẤU trọng tâm", -1);
    if (window.HANH_KHAC[hanhCung] === hs) return ket(`${hanhCung} khắc ${hs}`, "che_nhe", "Cung chế sao — nhẹ", 0);
    return ket("bình hòa", "binh", "Bình ổn", 0);
};

// ===== 3b. PHẢN NGÂM / PHỤC NGÂM cho MỘT sao (thay cho xetPhanPhucNgam trong phi-tinh.js,
// tnXetHopThapNgam trong tim-nha.js, và logic inline ngamHit trong cuu-cung-luoi.js —
// cả 3 nơi cùng 1 công thức, viết tay riêng lẻ 3 lần) =====
// sao: Sơn tinh hoặc Hướng tinh tại 1 cung · soGoc: số Lạc Thư nguyên đán cố định của đúng cung đó.
// Trả về {loai:"phuc"|"phan", nhan, ky} nếu trùng hoặc hợp thập với số gốc, ngược lại null.
window.xetPhanPhucNgamMotSao = function(sao, soGoc) {
    if (sao === soGoc) return { loai: "phuc", nhan: "Phục Ngâm", ky: "伏" };
    if (sao + soGoc === 10) return { loai: "phan", nhan: "Phản Ngâm", ky: "反" };
    return null;
};

// ===== 3c. CÁCH CỤC VƯỢNG SƠN VƯỢNG HƯỚNG / THƯỢNG SƠN HẠ THỦY (cấp toàn nhà — so sánh Sơn
// tinh/Hướng tinh tại đúng 2 vị trí Tọa và Hướng với số Vận nhà) — dùng chung cho tim-nha.js
// (tnCachCuoc cũ) và phi-tinh.js (trước đây chưa có khái niệm này, chỉ có gợi ý rút gọn theo
// từng cung riêng lẻ, không đúng bản chất "so Tọa với Hướng" của Vượng Sơn Vượng Hướng). =====
// sb=Sơn tinh tại Tọa, sf=Sơn tinh tại Hướng, hf=Hướng tinh tại Hướng, hb=Hướng tinh tại Tọa, van=Vận nhà.
window.xetVuongSuyCachCuc = function(sb, sf, hf, hb, van) {
    let vuongSon = sb === van;    // Sơn tinh về đúng Tọa — vượng nhân đinh
    let thuongSon = sf === van;   // Sơn tinh lạc lên Hướng (sai chỗ) — hại đinh
    let vuongHuong = hf === van;  // Hướng tinh về đúng Hướng — vượng tài lộc
    let haThuy = hb === van;      // Hướng tinh lạc xuống Tọa (sai chỗ) — hại tài
    let cachCuoc;
    if (vuongSon && vuongHuong) cachCuoc = "Vượng Sơn Vượng Hướng";
    else if (thuongSon && haThuy) cachCuoc = "Thượng Sơn Hạ Thủy";
    else {
        let labels = [];
        if (vuongSon) labels.push("Vượng Sơn");
        if (thuongSon) labels.push("Thượng Sơn");
        if (vuongHuong) labels.push("Vượng Hướng");
        if (haThuy) labels.push("Hạ Thủy");
        cachCuoc = labels.join(" + ") || null;
    }
    return { vuongSon, thuongSon, vuongHuong, haThuy, cachCuoc };
};

// ===== 3d. HỢP THẬP (V+S=10 hoặc V+H=10 tại 1 cung — thông khí, cứu cục) =====
// Tách riêng khỏi Phản/Phục Ngâm (khác concept: Ngâm so sánh S/H với số Lạc Thư NGUYÊN ĐÁN của
// cung; Hợp Thập so sánh S/H với chính VẬN TINH tại cùng cung đó).
window.xetHopThap = function(v, s, h) {
    return { hopThapVS: v + s === 10, hopThapVH: v + h === 10 };
};

// ===== 3e. ĐỊNH CHÂN KHÍ — Hà Đồ (Tiên Thiên), TÁCH RIÊNG hoàn toàn khỏi HANH_CUA_SAO (Lạc Thư/
// Hậu Thiên) ở trên. Hai bảng số→hành này KHÁC NHAU thật sự (ví dụ số 9: Lạc Thư=Hỏa, Hà Đồ=Kim)
// — không được dùng lẫn cho nhau. =====
// Hà Đồ nguyên bản có 5 cặp sinh-thành: 1&6=Thủy, 2&7=Hỏa, 3&8=Mộc, 4&9=Kim, 5&10=Thổ. Ka chỉ nêu
// 4 cặp đầu (vì Hướng nhà — 1 trong 8 cung — không bao giờ ra số 5); riêng số 5 vẫn cần có hành để
// xử lý khi VẬN là 5 (Vận Ngũ Hoàng, từng xảy ra 1944-1963) — tạm điền theo đúng cặp gốc 5&10=Thổ,
// CẦN KA XÁC NHẬN LẠI cho chắc vì đây là phần tự suy luận thêm, không phải nguyên văn Ka cung cấp.
window.HA_DO_NGU_HANH = { 1: "Thủy", 6: "Thủy", 2: "Hỏa", 7: "Hỏa", 3: "Mộc", 8: "Mộc", 4: "Kim", 9: "Kim", 5: "Thổ" };

// So Ngũ hành Hà Đồ của VẬN hiện tại (Thiên thời) với Ngũ hành Hà Đồ của HƯỚNG nhà (Địa lợi).
// soCungHuong: số Lạc Thư CỐ ĐỊNH của cung chứa Hướng nhà (Khảm=1, Khôn=2,... Ly=9 — dùng số cố
// định của phương vị, KHÔNG dùng Hướng tinh bay theo Vận, để giữ đúng tính chất Tiên Thiên/bất biến).
window.xetChanKhiHaDo = function (vanSo, soCungHuong) {
    let hanhVan = window.HA_DO_NGU_HANH[vanSo];
    let hanhHuong = window.HA_DO_NGU_HANH[soCungHuong];
    if (!hanhVan || !hanhHuong) return null;
    if (hanhVan === hanhHuong || window.HANH_SINH[hanhVan] === hanhHuong) {
        return { hanhVan, hanhHuong, loai: "dac", nhan: "Đắc Chân Khí", moTa: "Vận sinh Hướng (hoặc đồng hành) — khí vào nuôi dưỡng nhà, cực tốt." };
    }
    if (window.HANH_SINH[hanhHuong] === hanhVan) {
        return { hanhVan, hanhHuong, loai: "tiet", nhan: "Bị Tiết Khí", moTa: "Hướng sinh Vận — nhà hao tổn khí nhẹ, mức bình thường." };
    }
    if (window.HANH_KHAC[hanhVan] === hanhHuong || window.HANH_KHAC[hanhHuong] === hanhVan) {
        return { hanhVan, hanhHuong, loai: "that", nhan: "Thất Chân Khí", moTa: "Vận khắc Hướng hoặc Hướng khắc Vận — đại kỵ, dù Phi Tinh bay đẹp cũng khó bền." };
    }
    return { hanhVan, hanhHuong, loai: "binh", nhan: "Bình hòa", moTa: "Không sinh không khắc rõ rệt." };
};

// ===== 3f. TỔ HỢP SƠN TINH – HƯỚNG TINH (64 quẻ, cát/hung chi tiết theo từng cặp số cụ thể) =====
// Nguồn: tài liệu Ka cung cấp — "Luận 2 sao Sơn - Hướng" (81 tổ hợp đầy đủ, ứng mỗi cặp số với 1
// trong 64 quẻ Dịch, có luận Sinh vượng và Khắc sát riêng).
//
// QUY ƯỚC THỨ TỰ KHÓA — QUAN TRỌNG, DỄ NHẦM: khóa "X-Y" nghĩa là HƯỚNG TINH = X, SƠN TINH = Y
// (không phải Sơn trước Hướng sau). Đã xác nhận qua đúng 2 ví dụ nêu trong tài liệu gốc:
//   - "1 6, thì 1 là hướng tinh, 6 là sơn tinh" → khóa "1-6" = Thủy Thiên Nhu (khớp)
//   - "4 3, 4 là sơn tinh, 3 là hướng tinh" → khóa "3-4" = Lôi Phong Hằng (khớp)
// Tên quẻ được ghép là [quái của Hướng tinh] + [quái của Sơn tinh] theo đúng thứ tự đó.
window.TO_HOP_SON_HUONG = {
    "1-1": { quaiTen: "Khảm Vi Thuỷ", sinhVuong: "Sinh con thông minh, túc trí đa mưu, thi cử đỗ đạt, nổi tiếng khắp nơi. Hai Thuỷ tỷ hoà, tiên của dư dật, sự nghiệp phát đạt phát tài ngoài luồng, khởi nghiệp bằng nghề buôn muối và cá. Đầu năm thuận lợi, nhưng dương thịnh âm suy, đề phòng phụ nữ chết trẻ, lâu thl nhân khẩu giảm.", khacSat: "Mắc bệnh tim, đau tai, bệnh về máu, thận và bệnh về hệ thống tiết niệu, bệnh sa nang, di tinh, băng huyết, đào hoa, có thói trăng hoa, phạm tội trộm cáp, là dân giang hồ. Nếu hình thế của núi và dòng nước xẩu thì chủ thiếu nam chết chim hoặc thắt cổ chết nếu hình thế của núi và dòng nước rời rạc thì chủ người trẻ (thiếu niên) đồng tính luyến ái." },
    "1-2": { quaiTen: "Thuỷ Địa Tỷ", sinhVuong: "Nhân khẩu đông đúc, thích hợp với công việc trong khách sạn, quán trà. Công việc đóng áng thuận lợi, công bằng chính trực, kiên trì với điều thiện, phát minh sáng tạo cái mới.", khacSat: "Bị mất nước, báng nước, bệnh dạ dày, xuất huyết dạ dày, viêm lá lách, nhiễm trùng máu, thiếu máu, tiểu đường, bệnh scorbut (bệnh về máu do thiếu vitamin c trong thức ăn), mất máu vùng bụng, viêm ruột thừa, cổ họng sưng đau, liệt dương, người trẻ hay bệnh tật bệnh phụ khoa, phụ nữ đổ máu bị sát hại. Khác thứ nam hoặc trung nam, làm suy giảm nhân đinh trong nhà. Mẹ con bất hoà, trung nam bị phụ nữ làm nhục, chủ người trẻ bị người đã có chồng lôi cuốn. Nếu có núi cao thì không có lợi cho mệnh Khảm." },
    "1-3": { quaiTen: "Thủy Lôi Truân", sinhVuong: "Phải trải qua nhiều gian khổ, tay không gây dựng sự nghiệp. Lợi cho con cháu chi trưởng, giàu có vinh hiển. Thi cử đỗ đáu, gia đình hoà thuận. Thuỷ Mộc tương sinh, có tài thao lược.", khacSat: "Chủ mắc bệnh gan, bệnh về chân, phù thũng, đau chân, khó sinh, hoa mắt bệnh thận, trướng bụng. Thanh niên bị chết đuối, nếu gặp Khách tinh Thất Xích đề phòng bị rắn cắn, chó cắn và bị sét đánh. Nếu gặp Khách tinh Thất Xích bay tới mà lại phạm thế Xuyên sơn sát là điềm báo nhà tan người mất. Lâm vào hoàn cảnh khó khăn, ít con nối dõi, tranh chấp, cãi cọ, hao tổn sinh khí, kiện tụng, trộm cắp, hao tài tốn của. Nếu hình thế của dòng nước xấu thì chủ thanh niên gặp vận hạn, nếu hình thế của núi xấu thì chủ người trẻ bị sét đánh." },
    "1-4": { quaiTen: "Thủy Phong Tình", sinhVuong: "Thi cử đỗ đạt, có tiếng tăm. Vợ bé sinh quỷ tử, giỏi văn chương thi hoạ, là danh sĩ phong lưu, chấp pháp nghiêm minh, trong sạch liêm khiết Người này thích hợp làm trong công ty con của tập đoàn tài chính, thuận lợi trong giao dịch trên giấy tờ, khế ước. Đi xa gặp thuận lợi, được tăng lương và thăng quan tiến chức.", khacSat: "Chủ bệnh phong thấp, bệnh ở vú, vú chảy máu, xuất huyết khí quản, bệnh về gan và mật tinh thần không ổn định. Đam mê tửu sắc, nam nữ dâm loạn, phạm tội bị truy nã. Nếu Nhất Bạch suy, Mộc tiết làm yếu Thuỷ thì chủ chị dâu em chồng dan díu với nhau. Nếu hình thế dòng nước xấu thì chủ phụ nữ trẻ chết đuối. Nếu hình thế của núi xấu thì chủ người trẻ gặp hạn, nếu hình thế của nước dâm thì chủ người trẻ yêu phụ nữ đã có chồng, chị gái em trai hoặc chị dâu em chồng loạn luân (nam chủ động). Nếu là người nắm quyền thì chủ tham ô hối lộ mà phạm pháp." },
    "1-5": { quaiTen: "Không Quẻ", sinhVuong: "Thi cử đỗ đầu, thường sinh con trai thông minh tài giỏi, tăng nhân khẩu. Thích hợp làm chuyên gia thuỷ lợi, nhà phát minh.", khacSat: "Chủ mắc bệnh ung thư (máu và tử cung), nhiễm trùng máu, bệnh thận, tăng urê huyết (viêm cầu thận), chứng mất nước, trường toan (nước chua) trong dạ dày không đủ, thận trúng độc, thiếu máu, bệnh giun móc, ngộ độc thai nghén, ngộ độc máu, ngộ độc rượu, xuất huyết dạ dày, bệnh truyền nhiễm qua đường tình dục, đau rát âm hộ, sỏi thận, phù thũng, vô sinh, sảy thai, nghiện hút, buôn bán ma tuý. Nếu hình thế núi xấu chủ người trẻ chết thảm, trung nam ngỗ nghịch." },
    "1-6": { quaiTen: "Thủy Thiên Nhu", sinhVuong: "Chủ thi cử đỗ đạt mang lại tiếng tăm, đến tuổi trung niên làm giàu một cách nhanh chóng, phát về nghiệp võ, thích hợp làm giáo viên và trợ lý, chủ sống lâu, mọi việc thuận lợi, thường ứng nghiệm với lưu niên 2 và 8\\.", khacSat: "Xuất huyết não, đần độn, thương hàn, chấn thương sọ não, xung huyết não, xuất huyết từ xương, tràn dịch màng phổi, sa dạ con, sa tinh hoàn, sa nang, sỏi thận, bệnh về thận. Cha con bất hoà, trộm cắp phạm pháp, hoang dâm vô độ, cần đề phòng bị chết đuối hoặc sống lưu lạc. Nếu hình thể của dòng nước xấu thl chủ người già gặp hạn, người trẻ bị thương do dao." },
    "1-7": { quaiTen: "Thủy Trạch Tiết", sinhVuong: "Nắm quyền, biết cách quản lý tài chính, là người khéo ăn khéo nói. Xuất hành thuận lợi, nam liêm khiết nữ chung thuỷ.", khacSat: "Chủ mắc bệnh phổi, phổi chảy máu, bé gái mắc bệnh thận, bệnh về tai, chứng câm điếc, thổ huyết đàm suyễn, di tinh, sảy thai, chó cắn, nhiễm trùng do rắn cắn. Đam mê tửu sắc, người nhà ly tán, nam nữ dâm. loạn, người trẻ bị tử hình, phụ nữ trung nam cãi cọ, trung nam lừa gạt thiếu nữ, keo kiệt độc ác, trộm cắp giết người. Nếu hình thế dòng nước xấu thì chủ bé gái bị chết chìm. Nếu hình thế núi xấu thì chủ thiếu niên bị đâm chết" },
    "1-8": { quaiTen: "Thủy Sơn Kiển", sinhVuong: "Có tài văn chương, học thức uyên bác. Khi biết lỗi thì biết hối cải, biết tự kiểm điểm mình, gặp hung hóa cát Công bằng chính trực, tài đức vẹn toàn. Thích hợp với những công việc gian khổ như khai thác mỏ, công trình thuỷ lợi.", khacSat: "Chủ mắc bệnh thận, sỏi thận, sỏi bàng quang, bệnh về mũi, thiếu máu, nhiễm trùng máu, trường toan quá ít, bệnh về tai, sỏi đường tiết niệu, tắc ống dẫn trứng, sỏi tử cung, người trẻ bị tâm thần, ngã xuống vực, chứng mất nước, đau lưng, tay bị thương, bị thương do thú vật vổ, sảy thai, kiết lỵ, trẻ nhỏ bị u, vẹo cột sống, trung nam lâm bệnh mà chết. Anh em bất hoà, khắc trung nam, phạm tội phải ngồi tù, vợ chồng ly dị. Nếu hình thế dòng nước xấu thi chủ bé trai chết chìm. Nếu hình thế núi xấu thì chủ người trẻ bị rơi xuống vực hoặc bị chó dại cắn, em giết anh. Nếu có núi cao là Dụng thần thì không có lợi cho mệnh Khảm." },
    "1-9": { quaiTen: "Thuỷ Hoả Ký Tế", sinhVuong: "Thuỷ Hoả Ký Tế, chủ vượng cả đinh lẫn tài. Âm dương cân bằng, giàu sang phú quý, công thành danh toại, vợ chồng hạnh phúc. Đức cao vọng trọng, tài cao học rộng. Tu tâm dưỡng tính, thay da đổi thịt, phúc trạch bén lâu.", khacSat: "Bệnh truyền nhiễm qua đường tình dục, bệnh da liễu, bệnh tim, bệnh thận, mù, bệnh về mắt, hay bị ám ảnh, sa nang, sảy thai. Vợ chồng bất hoà, ly dị, kiện tụng, trung nữ đoản mệnh. Phạm thượng làm loạn, bị trùng tang. Thuỷ hoá tai hoạ, kiện cáo triên miên. Thuỷ Hoả không dung hoà, hay làm điều trái khoáy. Nếu hình thế của dòng nước dâm thì chủ nam nữ dâm loạn. ### **CÁT HUNG CỦA NHỊ HẮC THỔ TINH VÀ Tổ HỢP cửu tinh**" },
    "2-1": { quaiTen: "Địa Thuỷ sư", sinhVuong: "Chủ vê sinh con, là nhân tài có khả năng lãnh đạo trong các ngành nghề. Biết trọng dụng người có tài, thành công nhờ quần chúng. Phát về ruộng đất hoa màu, có tài phát minh sáng chế.", khacSat: "Bệnh-phụ Khoa, bệnh dạ dày, bệnh tiểu đường, bệnh về cơ quan sinh dục, bệnh thận, sảy thai. Không có lợi cho trung nam, trung nam bị vô sinh. Ruộng đất của cải bị mất tranh cãi về đất đai. Gặp tai hoạ bất ngờ, chiến tranh, tiểu nhân, trộm cắp, xã hội đen." },
    "2-2": { quaiTen: "Khôn Vi Địa", sinhVuong: "Phát về ruộng đất của cải dư dật. Phát về nghiệp võ, hoặc gây dựng sự nghiệp bằng nghề kinh doanh kim khí, đất đai. Có tài nhưng thành đạt muộn, mẹ hiền từ, nhiều vốn liếng, có giáo dục. Tăng nhân khẩu, trong nhà có người là lương y. Nhưng sinh ra nhiêu góa phụ làm nên cơ nghiệp.", khacSat: "Bệnh về ruột và dạ dày, bệnh phụ khoa, đần độn, câm điếc. Phạm pháp và phải chịu hình phạt, hám của, vô đạo đức, dốt nát mê muội, thuộc lớp người thấp hèn. Vợ đoạt quyền chồng, khó sinh, sảy thai. Thường có goá phụ, bị tà khí xâm nhập, phụ nữ mác chứng cuông dâm." },
    "2-3": { quaiTen: "Địa Lôi Phục", sinhVuong: "Biết hối cải và hướng thiện, biết tu tâm dưỡng tính. Sống đúng với bản chất, luân hồi đầu thai, thai nghén tái sinh. Tích cực tiến thủ, biết đứng dậy sau khi vấp ngã. Biết phân biệt rõ đúng sai, tốt xấu.", khacSat: "Bệnh về chân, bệnh về dạ dày, chứng co giật, khớp gặp vấn đề, bệnh tình xấu đi hoặc bị tường đè làm bị thương. Con trưởng không nghe lời mẹ, nhà cửa không yên, người mẹ gặp tai hoạ, mẹ hiền con hư, mẹ ác con ác. Vì tham lam nên bị hại, cãi cọ, điều tiếng thị phi, thắt cổ tự tử, vì gia sản mà nhà cửa tan hoang, kiện tụng, phải chịu hình phạt, phụ nữ chết thảm, thanh niên hay ốm đau bệnh tật trưởng nam treo cổ tự vẫn. Nếu hình thế dòng nước xấu thì chủ thanh niên bị siết cổ chết Nếu hình thế núi xấu thì phụ nữ bị sét đánh, con giết mẹ, thanh niên loạn luân. Nếu có núi cao là. Dụng thần thì không có lợi cho người mệnh Khôn." },
    "2-4": { quaiTen: "Địa Phong thăng", sinhVuong: "Thích hợp làm nghé kinh doanh bất động sản, năng nhặt :chặt bị, vượng tài. Trúng thưởng, thăng chức, hơn hẳn mọi người, nâng cao chất lượng cuộc sống. Mẹ hiền, vợ đảm, con gái xinh đẹp, phụ nữ sang trọng.", khacSat: "Chủ mắc bệnh phong, hao tổn sinh khí, bệnh về bắp đùi, bệnh về mật, bệnh về vú, bệnh dạ dày, trúng gió, gặp vấn đề khi sinh. Trong nhà người mẹ hay buôn rầu, phụ nữ treo cổ tự vẫn, tranh chấp đất đai, vì tham lam mà mất của, mẹ chồng con dâu bất hoà, đàn ông sống không thọ. Bị trúng kế mắc lừa, bị rơi vào cạm bẫy. Nếu hình thể dòng nước xấu thì chủ về phụ nữ có chồng thắt cổ tự tử. Nếu hình thế núi xấu thì chủ về con gái nhục mạ mẹ, con dâu lừa gạt mẹ chồng. Nếu có núi cao là Dụng thần thì không có lợi cho người mệnh Khôn." },
    "2-5": { quaiTen: "Không Quẻ", sinhVuong: "Tăng nhân khẩu, phát về ruộng đất của cải, trong nhà có người làm ngành pháp luật, phát về nghiệp võ, lợi cho nghề y, mở hiệu thuốc hoặc nghề mai táng. Nếu làm nghề y thì trong nhà sẽ có người là bác sỹ nổi tiếng.", khacSat: "Chủ vé ốm đau bệnh tật, bệnh ung thư (dạ dày, đại tràng, thự: quản, da), bệnh dạ dày, viêm loét dạ dày, da lở loét ngộ độc, nghiện hút, mụn nhọt bệnh giun móc, sảy thai, đẻ non. Nhị Ngũ giao nhau tất sẽ tổn thương đển chủ nhân, cẫn đến cảnh mẹ góa con côi. Vợ chồng xích mích, hay gặp rủi ro, tranh chấp đất đai." },
    "2-6": { quaiTen: "Địa Thiên Thái", sinhVuong: "Chủ về làm giàu nhỏ, kinh doanh đất cát, đầu tư ít nhưng kiếm được nhiều, trong nhà người mẹ luôn khoẻ mạnh. Tinh thần thoải mái, vinh hoa phú quý. Cấp dưới trung thành, phò tá cấp trên, là người có lương tâm. Vượng gia đình lẫn tài, luôn tràn đầy sức sống.", khacSat: "Chủ mắc bệnh dạ dày, sa dạ dày, sỏi thận, bệnh phổi, bệnh đại tràng, phụ nữ đau đầu, sưng lá lách, lúc nóng lúc lạnh, tinh thần bất định, tà khí xâm nhập. Vợ chồng xích mích, người già gặp tai nạn đổ máu, thắt cổ tự vẫn, keo kiệt bủn xỉn, địa vị thấp hèn." },
    "2-7": { quaiTen: "Địa Trạch Lâm", sinhVuong: "Làm giàu nhanh chóng, trở thành tỷ phú. Mở rộng đất đai, dùng tiền bạc để sinh lời. Tăng nhân khẩu, thường sinh con gái, sinh quý tử. Trong nhà có người làm trong ngành y hoặc pháp luật, kiến thức uyên bác, hay làm điều thiện.", khacSat: "Chủ mắc bệnh dạ dày, bệnh đại tràng, bệnh phổi, bệnh vòm họng, bé gái mắc dịch tả, kiết lị, đau vai, sẩy thai. Vì thói trăng hoa mà mất của. Hai chồng khác con, kiện tụng, gặp tai họa bất ngờ. Con dâu út tinh tinh ngỗ nghịch, hay cãi cọ với nhà mẹ đẻ. Trong nhà người mẹ hay buồn phiền, tranh chấp đất đai. Gặp tai nạn về lửa, phụ nữ cuồng dâm. Nếu hình thể dòng nước xấu thì tổn thương đến bé gái. Nếu hình thể núi xấu thì tổn thương đến phụ nữ." },
    "2-8": { quaiTen: "Địa Sơn Khiêm", sinhVuong: "Làm giàu nhỏ nhờ đất đai, thích hợp với nghề kinh doanh bất động sản. Kính trọng người già, trong nhà có người hiền tài, sống hoà đồng, hiểu biết rộng, biết mềm nắn rắn buông, có lợi từ di chuyển.", khacSat: "Chủ mắc bệnh dạ dày, bệnh về ổ bụng, bệnh da liễu, bệnh về ngón tay, bệnh cột sống, bệnh thần kinh, bệnh về gân cốt, bệnh kết sỏi. Thiếu nam tính, tinh thần ngỗ nghịch, trong nhà người mẹ hay u sầu phiền muộn. Thành công ít thất bại nhiều, tranh chấp đất đai của cải, có nhiều quả phụ. Nếu hình thể dòng nước xấu thì tổn thương đến bé trai. Nếu hình thể núi xấu thì bị chó dại cắn, phụ nữ bị chết." },
    "2-9": { quaiTen: "Địa Hỏa Minh Di", sinhVuong: "Tăng nhân khẩu, trong nhà có người có giang (có thể là \"có giang hồ\" hoặc \"có danh tiếng\" – tùy ngữ cảnh). Đất đai mở rộng, của cải dư dật Có tài văn chương, thi cử thuận lợi. Như viên ngọc vùi trong cát có lợi lộc có công danh. Nhẫn nhục chịu đựng, quả phụ làm nên sụ nghiệp. Nếu gặp vận 2 thì của cải dùng không hết", khacSat: "Chủ mắc bệnh dạ dày, bệnh về máu, xuất huyết dạ dày, viêm dạ dày, viêm ruột thừa, bị tai nạn đổ máu, bệnh nhiệt, bệnh về mắt, bệnh tim, gặp rắc rối khi sinh nở, dạ dày tích nhiệt, viêm da, mất máu vùng bụng, cắt tử cung. Trong nhà người mẹ hay lo buồn, tranh chấp đất đai của cải, kiện tụng. Chống đối, đần độn, ít con, giảm nhân khẩu. Phạm tội giết người, sống dâm loạn, mất của. Nếu hình thể dòng nước xấu thì làm hại đến thiếu nữ. Nếu hình thể núi xấu thì phụ nữ gặp hạn. --- ### **CÁT HUNG CỦA TAM BÍCH MỘC TINH VÀ TỔ HỢP CỬU TINH**" },
    "3-1": { quaiTen: "Lôi Thủy Giải", sinhVuong: "Thủy Mộc tương sinh, gia đình hoà thuận, chủ về phú quý. Sinh con phát tài, thi cử thuận lợi. Phạm tội được giảm án, mãn hạn tù, chịu hình phạt lại được trọng dụng. Biết cách hoà giải tranh chấp, được gặp gỡ người quyền quý.", khacSat: "Kiện tụng, khắc mẹ, tổn thương dạ dày, gia đình ly tán, con trưởng đi khỏi nhà, tổn hại đến phụ nữ, ít con cháu. Tranh cãi, kích động, hao của." },
    "3-2": { quaiTen: "Lôi Địa Dự", sinhVuong: "Đắc tài, thành danh, thích hợp với những nơi như khách sạn, thương trường. An cư lạc nghiệp, thay da đổi thịt, tu tâm dưỡng tính, sống chân thật, lương thiện.", khacSat: "Chủ về dạ dày bị tổn thương, sắc mặt vàng vọt. Đầu Ngụu sát, chủ về kiện tụng, khắc mẹ, tai họa bất ngờ giáng xuống đầu, kích động, hao tài tốn của, tranh chấp đất đai tài sản. Trưởng nam chống lại mẹ, điều tiếng thị phi, trước ảnh hưởng đến người mẹ, sau ảnh hưởng đến chi trưởng." },
    "3-3": { quaiTen: "Chấn Vi Lôi", sinhVuong: "Tài lộc dồi dào, có thể sáng lập sự nghiệp gây dựng cơ đồ. Lợi về đường công danh, lợi cho chi trưởng. Thi cử thuận lợi, luôn là người đứng đầu.", khacSat: "Chủ mắc bệnh gan, tai nạn đổ máu, đau chân, bệnh tâm thần, chứng hoang tưởng. Kiện tụng, tranh chấp, phạm tội giết người, phụ nữ chết yểu, trẻ con khó nuôi, trong nhà có người đần độn. Dâm loạn, chi trưởng bị phạt đánh bằng trượng. Động đất, côn trùng cắn, ngã bị thương, hao tốn tiền của. Nếu hình thể núi hoặc dòng nước xấu thì chủ thanh niên bị sét đánh. Nếu hình thể núi hoặc dòng nước đâm thì chủ nam giới dâm loạn." },
    "3-4": { quaiTen: "lôi Phong hằng", sinhVuong: "Chủ phú quý, lợi vé đường công danh, gia đinh hoà thuận, sinh sôi, vợ chồng đồng tâm hiệp lực. Trăm sự thuận lợi, giữ vững lập trường. Nam lấy được vợ sang trọng, sống hạnh phúc đến già, luôn thích ứng trong mọi hoàn cảnh. Bền bỉ, đức hạnh, sống có đạo lý.", khacSat: "Chủ mắc bệnh gan, đau chân, chân bị thương, bệnh về bắp đùi, bệnh về vú, bệnh phong, hao tổn sinh khí, gặp rắc rối khi sinh nở. Treo cổ tự vẫn, không hiểu lý lẽ, làm việc tùy tiện, đam mê tửu sắc, trong nhà có người theo nghề trộm cắp, ăn xin. Chi trưởng có tiếng tăm không tốt, tốt xấu lẫn lộn, vong ân bội nghĩa, luôn dựa dẫm người khác, công việc không ổn định. Nếu hình thể dòng nước xấu thì tổn hại đến phụ nữ đã có chồng, hoặc vợ chồng trẻ xích mích. Nếu hình thể núi xấu thì chủ vợ hại chồng. Nếu hình thể núi dâm thì chủ nam nữ dâm loạn." },
    "3-5": { quaiTen: "Không Quẻ", sinhVuong: "Tài lộc dồi dào, gây dựng cơ nghiệp, chồng giàu sang phú quý, trong nhà có người làm quan lớn, góp công xây dựng đất nước, thành lập doanh nghiệp tư nhân, lợi cho ngành nông lâm, chi trưởng giàu sang phú quý.", khacSat: "Chủ mắc bệnh gan, ung thư gan, chân lở loét, nghiện hút, bị rắn cắn, bệnh dịch, nếu Tam, Tứ gặp nhau thì chủ bị trúng gió, ngã bị thương, sưng bầm, tai nạn xe cộ, bệnh phong, ham cờ bạc làm khuynh gia bại sản. Gặp tai họa bất ngờ, kiện tụng triền miên, động đất, sét đánh. Nếu hình thể núi xấu thì chủ thanh niên bị hạ độc mà chết. Nếu có dòng nước lớn là Dụng thần thì lợi cho cung Ngũ. ---" },
    "3-6": { quaiTen: "Lôi Thiên Đại Tráng", sinhVuong: "Lợi cho chi trưởng, được cấp trên đề bạt. Thích hợp làm kiến trúc sư, danh lợi song toàn. Thành đạt vào độ tuổi trung niên, sau khi thành đạt thì ẩn mình, công bằng chính trực, hay làm việc thiện.", khacSat: "Chủ mắc bệnh gan, bệnh não, bệnh về chân, đau bắp chân, ngã bị thương, ngã chết, bị tai nạn đổ máu, tai nạn xe cộ, bị thương do dao, chấn thương sọ não, kết sỏi gan, xơ gan. Trộm cắp, giết người, bị sét đánh, tổn thương đến trưởng nam, ngã ngựa, gãy chân. Kiện tụng, phải ngồi tù, điều tiếng thị phi, thích đao to búa lớn, thích khoe sức khoe tài, không biết điểm dừng. Nếu hình thể dòng nước xấu thì chủ xà nhà rơi trúng người cha. Nếu hình thể núi xấu thì chủ thanh niên bị thương, cha giết con. Nếu hình thể núi dâm thì chủ người cha có tụ tinh. Nếu có núi cao là Dụng thần thì không có lợi cho người mệnh Càn." },
    "3-7": { quaiTen: "Lôi Trạch Quy Muội", sinhVuong: "Tăng nhân khẩu, thêm tiền tài, thích hợp với ngành nghề dịch vụ. Nữ lấy được chồng quý, danh lợi song toàn.", khacSat: "Chủ mắc bệnh gan, bệnh vòm họng, đau chân, bệnh đại tràng, ngã bị thương, ngã bị chết, thổ huyết, bị tai nạn đổ máu. Tai nạn xe cộ, Xuy Vưu sát, kiện tụng, giết người, trộm cướp, tính tình hung bạo, chuyên gây rắc rối, điều tiếng thị phi, nam trộm cắp, nữ làm gái nhà hàng, ma quỷ vào nhà, con cháu không có hiếu. Nếu hình thể dòng nước xấu thì chủ bé gái bị xe cán. Nếu hình thể núi xấu thì chủ thanh niên gặp hạn. Nếu hình thể núi dâm thì chủ gia đình loạn luân. Nếu có núi cao là Dụng thần thì không có lợi cho người mệnh Chấn." },
    "3-8": { quaiTen: "Lôi Sơn Tiểu Quá", sinhVuong: "Con cái trong nhà thông minh, có tài văn chương, đông con nhiều cháu. Lợi cho việc xây dựng, trồng cây, làm rừng, phát về ruộng đất. Được anh em, bạn bè tôn trọng, thật thà chất phác, trung hiếu.", khacSat: "Chủ mắc bệnh dạ dày, bệnh về ngón tay, bệnh cột sống, bệnh về gân cốt, bệnh về xương, bệnh về cánh tay, bệnh thần kinh, kết sỏi, gan kết sỏi, da mặt vàng, trướng bụng, chán ăn, thở khò khè, đẻ non. Tổn hại đến bé trai, tổn hại đến nhân khẩu, mất mát tiền của, nhảy lầu ngã chết, bị ngã tổn thương vùng đầu, chân tay đều có bệnh, bàn chân và bàn tay dị dạng, không có chân tay, không có tứ chi, trượt chân ngã xuống vách núi. Anh em bất hoà, không có lợi cho trẻ em trong nhà, mất mát tiền của. Nếu hình thể dòng nước xấu thì chủ bị chó dại cắn. Nếu hình thể dòng nước dâm thì chủ thanh niên dâm loạn. Nếu có dòng nước lớn là Dụng thần thì không có lợi cho người thuộc cung 8\\." },
    "3-9": { quaiTen: "Lôi Hỏa Phong", sinhVuong: "Sinh con thông minh, phú quý song toàn. Mộc Hỏa sáng láng, tài năng xuất chúng. Phát về đất đai, của cải dư dật, phụ nữ gây dựng cơ đồ. Thi cử thuận lợi, thăng quan tiến chức, làm rạng danh gia đình.", khacSat: "Chủ mắc bệnh gan, bệnh về bàn chân và bắp chân, bệnh về mắt, bệnh về máu, ung thư máu, chứng viêm, bệnh nhiệt, bị bỏng, bị lửa thiêu, gặp rắc rối khi sinh nở, cảm nắng, bệnh tim. Bị vật nổ gây thương tích, hao tổn nhân khẩu, keo kiệt, mất mát tiền của. Phụ nữ đắc tội với anh chồng, nam trộm cắp, nữ làm gái nhà hàng. Nếu hình thể núi xấu thì chủ hỏa hoạn gây thương tích. Nếu hình thể dòng nước xấu thì chủ gia đình loạn luân. --- ### **CÁT HUNG CỦA TỨ LỤC MỘC TINH VÀ TỔ HỢP CỬU TINH**" },
    "4-1": { quaiTen: "Phong Thủy Hoán", sinhVuong: "Con cái thi cử đỗ đạt, thành danh, có tài văn chương, con gái xinh...đẹp, lấy chồng giàu sang phú quý. Tài vận tốt, tuổi thọ cao. Lợi xuất hành, thích hợp đến nơi khác để mưu cầu danh lợi.", khacSat: "Mắc bệnh thận, gan, thiếu máu. Phụ nữ sống buông thả, phóng đãng, nếu có núi mà không có dòng chảy thì chủ vợ bé sinh con. Dâu trưởng thông dâm với em chồng. Có mâu thuẫn, thành công ít thất bại nhiều, tiến thoái lưỡng nan. Hợp lâu ắt sẽ tan, sa vào cuộc sống giang hồ." },
    "4-2": { quaiTen: "Phong Địa Quán", sinhVuong: "Có người là doanh nhân, kiến thức uyên bác, thích hợp phát triển ngành nông nghiệp, du lịch, thầy địa lý.", khacSat: "Đau gan, trướng bụng, bệnh giun móc, phụ nữ khó sinh, lao lực, sưng lá lách, hao tổn nhân đinh, mất mát tiền của, kiện tụng, tranh chấp, có tang, mất người mất của, tai họa tới tấp, trong nhà có người phụ nữ lừa gạt mẹ chồng, hoặc con gái sỉ nhục mẹ." },
    "4-3": { quaiTen: "Phong Lôi Ích", sinhVuong: "Vượng cả đinh lẫn tài, phú quý song toàn. Lợi về nghiệp văn chương, đầu tư sinh lời. Phát triển ngành nông lâm, được người phụ nữ sang trọng giúp đỡ. Gặp người hiền tài khiến mình phải suy ngẫm lại và nên làm việc thiện, thăng quan tiến chức, công thành danh toại.", khacSat: "Dễ mắc bệnh gan, thiếu nữ bị điên. Không hiểu lý lẽ, làm việc tùy tiện.Con gái cả gây gổ với chồng, sống phóng đãng, bại hoại gia phong. Làm tan nát nhà cửa, ảnh hưởng nhất đối với chi giữa, phụ nữ đoạt quyền chồng, làm giả giấy tờ, làm điều mờ ám, thường có người đi trộm cắp, ăn xin." },
    "4-4": { quaiTen: "Tốn Vi Phong", sinhVuong: "Lợi về nghiệp văn chương, có nhiều danh vọng, thi cử thuận lợi. Sinh con gái xinh đẹp, lấy chồng giàu sang, cũng vượng cả đinh lẫn tài. Sự nghiệp văn chương phát triển, tài tử giai nhân, lợi xuất hành.", khacSat: "Chủ mắc bệnh về vú, bệnh về bắp đùi, bệnh phong thấp, gặp rắc rối khi sinh nở, hen suyễn, ho. Con gái cả gây gổ với chồng, chi trưởng có tiếng xấu, mất chồng, giảm nhân khẩu, có người sống phóng đãng. Buông thả phá tài, đàn ông không thọ. Dùng sắc đẹp để mê hoặc lòng người, không biết hổ thẹn. Nếu hình thể núi và dòng nước dâm thì chủ phụ nữ đồng tính luyến ái. Nếu hình thể núi hoặc dòng nước xấu thì chủ phụ nữ trẻ mất mạng." },
    "4-5": { quaiTen: "Không Quẻ", sinhVuong: "Có người giỏi văn chương, là người phụ nữ thành đạt, là công nhân giỏi, là người thợ khéo, có tiếng tăm và khí phách, sự nghiệp phát triển thuận lợi.", khacSat: "Chủ mắc bệnh ung thư vú, ung thư gan, bệnh về vú, bệnh về mặt, bệnh phong, hao tổn sinh khí, gặp rắc rối khi sinh nở, mụn nhọt, thiếu phụ mắc bệnh do khí độc xâm nhập, viêm gan, bệnh dịch, bệnh dạ dày, bệnh điên, chứng nhiễm trùng huyết. Gặp tai họa chết chóc, buôn lậu ma túy, cờ bạc đầu cơ trục lợi, phá sản, mất của, sống phóng đãng, thân bại danh liệt. Nếu hình thể núi và dòng chảy dâm thì chủ thiếu phụ mất mạng. Nếu có dòng chảy lớn là Dụng thần thì không có lợi cho người thuộc cung Ngũ." },
    "4-6": { quaiTen: "Phong Thiên Tiểu Súc", sinhVuong: "Danh lợi song toàn, thăng quan tiến chức, gặp nhiều cơ hội, cạnh tranh đắc thắng. Nên phát triển ngành nông nghiệp và chăn nuôi, đầu tư ít thu lợi nhiều. Có tài văn nghệ, con gái cả nắm quyền, lấy chồng giàu sang, chuyện phiền hà có nhưng rồi lại hết.", khacSat: "Chủ mắc bệnh về mặt, bệnh phổi, bệnh ở vú, chứng đờm, hao tổn sinh khí, trúng gió, sảy thai, bệnh về bắp đùi, bệnh về đầu và mặt, bệnh não, bệnh đại tràng, sỏi mật, sưng phổi, sa dạ dày, gân cốt nhức mỏi, xơ gan. Đề phòng tự vẫn, tổn hại đến trưởng nữ, vất vả, người nhà ly tán, kiện tụng, trộm cắp, thiếu phụ phạm tội giết người. Nếu hình thể dòng nước xấu thì chủ người già chết. Nếu hình thể núi xấu thì chủ thiếu phụ mất mạng. Nếu có núi cao là Dụng thần thì không có lợi cho người mệnh Tốn, thuộc cung Tứ Lục." },
    "4-7": { quaiTen: "Phong Trạch Trung Phu", sinhVuong: "Là người có tướng mạo xinh đẹp, là người nắm quyền, thành thật, có uy tín, thẳng thắn vô tư.", khacSat: "Mắc bệnh về mặt, bệnh phổi, bệnh về vú, sưng phổi, bệnh về bắp đùi, bệnh phong, hao tổn sinh khí, bệnh vòm họng, bệnh đại tràng, phong thấp, chảy máu, bị thương do dao, xơ gan, bệnh về mắt. Âm thịnh dương suy, vợ chồng bất hoà, tổn hại con cái thông minh, đàn ông không thọ. Kiện tụng, tranh chấp, ngồi tù, mất của, gian trá, giết người, đào hoa, kém tài kém sắc. Chị em bất hoà, không có tài văn chương. Nếu hình thể dòng nước xấu thì dâm loạn, không có lợi cho người mệnh Tốn." },
    "4-8": { quaiTen: "Phong Sơn Tiệm", sinhVuong: "Theo nghề đông y, cây cảnh, là người thanh nhàn, làm giàu nhờ nghề nông lâm và chăn nuôi. Làm điều thiện sẽ được hưởng điều tốt lành.", khacSat: "Mắc bệnh về lá lách và dạ dày, bệnh về ngón tay và cánh tay, hao tổn sinh khí, bệnh phong, bệnh về mặt, bệnh về vú, bệnh cột sống, hen suyễn, thiếu phụ....mắc bệnh tinh thần, bệnh phong thấp. Anh em bất hòa, chị dâu em chồng thông dâm. Không có lợi cho chi út, con gái cả sảy thai tử vong. Mất của, sống phóng đãng, có con riêng. Nếu hình thể núi xấu thì không có lợi cho người mệnh Cấn, thuộc cung 8\\." },
    "4-9": { quaiTen: "Phong Hỏa Gia Nhân", sinhVuong: "Con cái thông minh, có con gái giỏi giang, vợ hiền gây dựng cơ nghiệp, phát về chi trưởng, hay làm điều thiện.", khacSat: "Mắc bệnh viêm, bệnh về máu, viêm phế quản, bệnh về mắt, bệnh về mặt, bệnh phong, bệnh tim, tai nạn đổ máu, hỏa hoạn, bệnh dịch, chóng mặt hoa mắt. Tự tử, có người bị gù. Không có lợi cho thiếu phụ trong nhà, không giữ gìn khí tiết, làm bại hoại gia phong, dính líu đến vụ bê bối tình dục, trong nhà có người trộm cắp, bị chê bai. Hình thể núi và dòng nước xấu, nếu có 2 người phụ nữ ở trong một nhà thì nhà này sẽ tuyệt tự. ### **CÁT HUNG CỦA NGŨ HOÀNG THỔ TINH VÀ TỔ HỢP CỬU TINH**" },
    "5-1": { quaiTen: "Ngũ Nhất Song Tinh", sinhVuong: "Tư duy nhanh nhạy, tràn đầy sức sống, là nhà tư tưởng, chuyên gia thủy sản, thủy lợi, nhà động lực học. Rất nhạy cảm và kín đáo.", khacSat: "Mắc bệnh về bàng quang, ung thư, nhiễm trùng máu, chứng tăng urê huyết, bệnh về đường sinh dục, xuất huyết dạ dày, viêm tai giữa, điếc, vô sinh. Buôn ma túy, chết do tai nạn bất ngờ, chết đuối, trộm cắp. Nếu có dòng nước lớn là Dụng thần thì không có lợi cho người mệnh Khảm." },
    "5-2": { quaiTen: "Ngũ Nhị Song Tinh", sinhVuong: "Tăng nhân khẩu, mở rộng đất đai của cải. Thích hợp làm quan tòa, bác sĩ, đạo sĩ, chính trị gia.", khacSat: "Chứng đau nhức, bệnh dạ dày, ngộ độc, nghiện hút, mụn nhọt, bệnh giun móc, cảm điếc, đần độn, hôn mê, bệnh về đường sinh dục ở nữ, ung thư, bệnh da liễu, gặp rắc rối khi sinh nở, trong nhà dễ có người thành quả phụ, chồng không thọ. Tranh chấp đất đai, tài sản, tà khí xâm nhập." },
    "5-3": { quaiTen: "Ngũ Tam Song Tinh", sinhVuong: "Trong nhà có người làm quan lớn được hưởng nhiều bổng lộc, thành tích chính trị vẻ vang, đẩy danh vọng. Lập công lớn, thích hợp phát triển ngành nông lâm nghiệp.", khacSat: "Mắc bệnh gan, ung thư gan, chân lở loét, thanh niên nghiện hút, tai nạn đổ máu, bệnh dịch. Rắn cắn, trộm cắp, giết người, chết đột ngột ngoài đường, tai nạn....xe cộ, điện giật, sống dâm dật. Con lừa cha, con dâu gây gổ với mẹ chồng, trưởng nam lâm bệnh nặng, nghèo khổ bệnh tật lại gặp tai ương." },
    "5-4": { quaiTen: "Ngũ Tứ Song Tinh", sinhVuong: "Trong nhà có người làm nhà văn, nhà thơ, họa sĩ, quan tòa, người phụ nữ sang trọng, người phụ nữ đức hạnh, người giỏi khí công, người thợ khéo léo.", khacSat: "Bệnh ung thư, bệnh về mặt, bệnh phong, hao tổn sinh khí, gặp rắc rối khi sinh nở, mụn nhọt, bệnh giun móc, bệnh dịch, bệnh dạ dày, trẻ em bị liệt, bệnh về vú, bệnh mẩn ngứa, bệnh hủi. Buôn ma túy, nghiện hút, ngộ độc. Ham mê cờ bạc, nghiện rượu, giết người, làm mất hết đất đai sản nghiệp, thân bại danh liệt, làm bại hoại thuần phong mỹ tục, không có lợi cho người thuộc cung Ngũ." },
    "5-5": { quaiTen: "Ngũ Ngũ Song Tinh", sinhVuong: "Là nhà sưu tầm, nhà buôn đồ cổ, quý nhân giàu có, tài năng xuất chúng, người nắm quyền, tạo dựng công trạng sự nghiệp, đông con nhiều cháu.", khacSat: "Bệnh ung thư, mụn nhọt, bệnh giun móc, bệnh dạ dày, bệnh dịch, cảm điếc, đần độn, xuất huyết não, bệnh truyền nhiễm, gặp rắc rối khi sinh nở. Tai nạn bất ngờ, kiện tụng, dâm loạn, giảm nhân khẩu, mất mạng 5 người." },
    "5-6": { quaiTen: "Ngũ Lục Song Tinh", sinhVuong: "Là người chỉ huy, khai quốc công thần, bậc thánh nhân, người lương thiện, tôn thờ Phật giáo và Đạo giáo.", khacSat: "Bệnh dạ dày, bệnh đại tràng, bệnh phổi, ung thư (dạ dày, phổi, đại tràng), đau mọc mụn, người già mất trí, người thực vật. Gặp tai họa, gây tổn hại cho gia chủ. Nếu hình thể dòng nước xấu thì chủ người già chết." },
    "5-7": { quaiTen: "Ngũ Thất Song Tinh", sinhVuong: "Là nhà ngôn ngữ, nhà ngoại giao, nhà bình luận. Yểu điệu thục nữ, xinh đẹp danh giá, có tài xuất chúng, là nhà tâm linh.", khacSat: "Bệnh phổi, bệnh vòm họng, bệnh về lưỡi, bệnh đại tràng, viêm gan, bệnh giun móc, ung thư (đại tràng, vòm miệng, lưỡi, phổi), ngộ độc thực phẩm, nghiện hút, mụn nhọt, bệnh về đường sinh dục, đần độn, hôn mê, thiếu phụ lâm bệnh nặng, tranh chấp đất đai tài sản. Nếu hình thể núi và dòng nước xấu thì chủ bé gái gặp tai họa." },
    "5-8": { quaiTen: "Ngũ Bát Song Tinh", sinhVuong: "Người đứng đầu, cảnh sát, thầy tu, trẻ con thông minh nhanh trí, phúc thọ song toàn, thật thà chất phác, có phúc phận.", khacSat: "Bệnh dạ dày, bệnh về mũi (ung thư), bệnh về ngón tay và cánh tay, bệnh...tinh thần, bong gân, gãy xương, bệnh cột sống, bệnh kết sỏi, đầu mọc mụn, cảm điếc, đần độn, bại liệt, đau thần kinh tọa. Thiếu nam nghiện hút, thiếu nam lâm bệnh nặng, tổn hại đến người trẻ. Nếu hình thể núi và dòng nước xấu thì chủ bé trai mất mạng." },
    "5-9": { quaiTen: "Ngũ Cửu Song Tinh", sinhVuong: "Nhà giáo dục, nhà quân sự, người có học vấn. Là người xinh đẹp, phụ nữ hào hiệp, phụ nữ sang trọng. Có tài xuất chúng, phú quý song toàn.", khacSat: "Bệnh về máu, bệnh tim, ung thư máu, ung thư đại tràng, viêm đại tràng, bệnh về mắt, bệnh mủ máu, chứng viêm, bệnh nhiệt, loét tá tràng, gặp rắc rối khi sinh nở, vô sinh, sảy thai, đẻ non, xuất huyết dạ dày, mụn nhọt. Trong nhà có người lâm bệnh nặng, không có lợi cho con gái giữa, dâm loạn, mất của. Ngũ \\- Cửu \\- Thất đồng cung chủ mắc bệnh về đường sinh dục, viêm kết mạc. Nếu hình thể núi và dòng nước xấu thì chủ thiếu nữ gặp tai họa. ### **CÁT HUNG CỦA LỤC BẠCH KIM TINH VÀ TỔ HỢP CỬU TINH**" },
    "6-1": { quaiTen: "Thiên Thủy Tụng", sinhVuong: "Có tài văn chương, học thức uyên bác. Là luật sư thanh bạch liêm khiết. Làm giàu từ ngành thủy lợi, có công gây dựng sự nghiệp. Dung mạo xinh đẹp, hiền lành lương thiện.", khacSat: "Bị thương vùng đầu, não xuất huyết, xuất huyết não, xuất huyết tủy xương, xuất huyết phổi, khí thũng, sỏi thận, sa dạ con, băng huyết, sảy thai, sa bàng quang, kiết lị, táo bón, di tinh, bệnh đại tràng. Kiện tụng, trung nam mất của, tranh chấp tài sản, gian nhân giả nghĩa, độc ác nham hiểm. Nếu hình thể núi và dòng nước xấu thì chủ người già dâm loạn, bị vướng vào vụ bê bối về tình dục." },
    "6-2": { quaiTen: "Thiên Địa Bĩ", sinhVuong: "Phát về đất đai, của cải dư dật. Là doanh nghiệp kinh doanh (không nên làm thương mại), vốn liếng nhiều. Vượng cả đinh lẫn tài, đông con, đa tài.", khacSat: "Bệnh dạ dày, sa dạ dày, dạ dày kết sỏi, bệnh phổi, bệnh đại tràng, đau đầu, đau cơ, bệnh phụ khoa. Cha mẹ lâm bệnh. Nếu hình thể núi và dòng nước xấu thì bị tà khí xâm nhập, dễ có người xuất gia." },
    "6-3": { quaiTen: "Thiên Lôi Vô Vọng", sinhVuong: "Có nước thì phát tài, được hưởng phúc bất ngờ, người già khỏe mạnh, về già có con, trong nhà có người làm quan.", khacSat: "Bệnh gan, chân bị khuyết tật, đau chân, bắp đùi bị khuyết tật, bệnh về não (suy nhược thần kinh), tai nạn đổ máu, tai nạn xe cộ, ngã bị thương, bị thương do dao. Tính tình ngông cuồng, cha con bất hoà, phụ nữ dâm loạn, tổn hại đến trưởng nam. Nếu hình thể núi và dòng nước xấu thì trong nhà có người vong ân bội nghĩa." },
    "6-4": { quaiTen: "Thiên Phong Cấu", sinhVuong: "Danh lợi song toàn, trong nhà có người giỏi cả văn lẫn vỗ. Nhân duyên tốt lấy con nhà quyền quý, vợ bé sinh quỷ tử.", khacSat: "Bệnh gan, bệnh phổi, bệnh về vú, sảy thai, bệnh phong, trúng gió, bệnh não, tai nạn đổ máu, bị thương do dao, tai nạn xe cộ, xơ gan. Mất vd hoặc tổn hại đến con gái cả, kiện tụng triền miên, hám của, sống phóng đãng. Nếu nước cung Tốn uốn quanh Càn thì chủ treo cổ xà nhà tự vẫn, không có lợi cho người thuộc cung Tứ Lục." },
    "6-5": { quaiTen: "Không quẻ", sinhVuong: "Thuộc gia đình giàu có, vượng và đinh lẫn tài. Trong nhà có người làm tướng lĩnh, chủ tịch tập đoàn tài chính.", khacSat: "Bệnh dạ dày, bệnh phổi, bệnh đại tràng, đau đầu, đau cổ, đau nhức xương, nhiễm trùng, bệnh ung thư (phổi, não, dạ dày), bị chém, tử hình. Cấp dưới mạo phạm cấp trên, bị đình chỉ công tác, sa thải, kiện tụng. Nếu hình thế núi hoặc dòng nước dâm thì trong nhà có người chết" },
    "6-6": { quaiTen: "Càn Vi Thiên", sinhVuong: "Giàu có, nhân khẩu đông đúc, dễ được cấp trên đề bạt Thích hợp làm về ngành máy móc, sản xuất kim loại. Có chí tiến thủ trong giới Phật học, hiểu biết hơn người.", khacSat: "Đau đầu, bệnh não, đau cổ, bệnh phổi, đau xương, bệnh đại tràng, tai nạn đổ máu. bệnh trung khu thần kinh. Hay dính líu đến kiện tụng, tuyệt tự, gây gổ với VỢ, cốt nhục tương tàn, giàu có mà không có con, cuộc sống lẻ loi hiu quạnh. Nếu hình thế núi và dòng nước xấu thì trong nhà có người sống dâm loạn." },
    "6-7": { quaiTen: "Thiên Trạch Lý", sinhVuong: "Thích hợp làm bộ đội, công an, nhân viên tư pháp. Ngoài ra cũng thích hợp làm trong ngành tài chính công thương, như kế toán, nhân viên tài vụ.", khacSat: "Bệnh phổi, bệnh vòm họng, đau đầu, đau nhức xương, bệnh đại tràng, tai nạn đổ máu, bị chém, bị thương do dao, viêm mũi. Cướp giật hợp tác không thành, đánh nhau, giải tán đoàn thể, nam nữ bất hoà, nữ xấu hơn nam, thường sinh con gái, con trai có nhiều con của vợ bé, tranh chấp tài sản, đấu kiếm gây thương tích. Nếu hình thế dòng nước xấu thì nam nữ loạn luân (ông già và gái trẻ)." },
    "6-8": { quaiTen: "Thiên Sơn Độn", sinhVuong: "Phát về nghiệp võ, là người nắm quyền, công thành danh toại. Thổ Kim tương sinh, đất đai bổng lộc nhiều. Cha hiền con hiếu thảo, chi út vượng nhân đinh. Phụ nữ không thọ, lâu thì tuyệt tự.", khacSat: "Bệnh phổi, đau đầu, bệnh não, đau cổ, bệnh đại tràng, đau nhức xương, bệnh dạ dày, bệnh thần kinh, đau ngón tay, bệnh cột sống, đau nhức gân cốt, bệnh kết sỏi, bệnh về mũi. Bị chém, bị điên. Cha không nuôi dưỡng con, công danh không có. Nếu hình thể núi và dòng nước xấu thì trong nhà có người loạn luân." },
    "6-9": { quaiTen: "Thiên Hỏa Đồng Nhân", sinhVuong: "Có tài văn chương, đức cao vọng trọng, là nhân vật nổi tiếng trong xã hội. Yêu thích thiên văn học, có danh tiếng.", khacSat: "Bệnh phổi, bệnh về máu, chứng viêm, xuất huyết não, não xuất huyết, bệnh về tuyến giáp trạng, đau cổ, đau nhức xương, bệnh đại tràng, bệnh nhiệt, bị thiêu chết, bị bỏng mà chết, sảy thai, gặp rắc rối khi sinh nở, vô sinh, sa dạ dày, bệnh về mắt. Bôn ba vất vả, cha và con gái bất hòa, con cái bất hiếu, con gái giữa ngỗ ngược với người già, nam nữ loạn luân. Nếu hình thể dòng nước xấu thì chủ thiếu nữ gặp tai nạn. Nếu hình thể núi xấu thì người già gặp tai nạn. Nếu hình thể núi tản mạn thì chủ thiếu nữ cặp bồ. Không có lợi cho người mệnh Càn, thuộc cung Lục Bạch. ### **CÁT HUNG CỦA THẤT XÍCH KIM TINH VÀ TỔ HỢP CỬU TINH**" },
    "7-1": { quaiTen: "Trạch Thủy Khốn", sinhVuong: "Người hiền lành, xinh đẹp, giỏi giang, thích hợp làm giáo viên, luật sư, bác sĩ, thầy bói. Được hưởng nhiều bổng lộc mà trở nên giàu có, có thể phát triển trong ngành chăn nuôi, thủy lợi, ao đầm, sông ngòi. Chi giữa vượng nhân đinh.", khacSat: "Bệnh phổi, xuất huyết phổi, khí thũng, bệnh thận, bệnh về tai, cảm điếc, thổ huyết. Sảy thai, đam mê tửu sắc, phạm tội bị lưu đày, giết người, nam nữ loạn luân, thiếu nữ trung nam tranh cãi, phá sản, bắt cóc, kiện tụng." },
    "7-2": { quaiTen: "Trạch Địa Tuy", sinhVuong: "Có người làm bác sĩ, quan tòa, cảnh sát, võ sư. Phụ nữ gây dựng cơ đồ, người mẹ chuyên lo liệu việc nhà, của cái ngày càng nhiều, hay làm điều thiện.", khacSat: "Bệnh đại tràng, bệnh dạ dày, bệnh phổi, bệnh vòm họng, bé gái đau bụng, tiêu chảy. Hỏa hoạn, phụ nữ dâm loạn, đàn ông đam mê tửu sắc. Không có lợi cho người thuộc cung Nhị Hắc, Ngũ Hoàng và Bát Bạch." },
    "7-3": { quaiTen: "Trạch Lôi Tùy", sinhVuong: "Đắc tài, có người văn võ song toàn, thích hợp làm trong ngành dịch vụ, giỏi văn nghệ. Vợ hiền trợ giúp cho chồng, vượng đinh vượng tài.", khacSat: "Bệnh gan, bệnh về mặt, bệnh vòm họng, bệnh đại tràng, đau chân, ngã bị thương, tai nạn đổ máu, thổ huyết. Bị thương do dao, tai nạn xe cộ, kiện tụng, giết người, tranh cãi, mất của. Bị người âm nhập, thiếu phụ mạo phạm với chồng, chi trưởng bất hoà, tổn hại đến chi trưởng, chiếm dụng phi pháp, cướp đoạt, vì nóng nảy mà gây tai họa. Nếu Tam, Thất, Cửu đồng cung thì thông minh, khắt khe, không có lợi cho người mệnh Tam Bích Mộc." },
    "7-4": { quaiTen: "Trạch Phong Đại Quá", sinhVuong: "Hiền lành xinh đẹp, giỏi văn giỏi võ, giỏi viết văn, nên phát triển trong ngành xuất bản.", khacSat: "Bệnh gan, bệnh phổi, bệnh về vú, khí thũng, đau bắp đùi, bệnh phong, bệnh phong thấp, bệnh vòm họng, bệnh đại tràng, tai nạn đổ máu, bị thương do dao, bị điên, tự vẫn, bị giết, đau chân, bị chết thảm. Đàn ông thường hoang dâm, phụ nữ thường dâm loạn. Tốt mã xấu xí, bất chấp thủ đoạn để làm giàu, chị em bất hoà. Không có lợi cho người thuộc cung Tứ Lục." },
    "7-5": { quaiTen: "Không Quẻ", sinhVuong: "Nhân khẩu đông đúc, giàu sang phú quý, dễ trở thành nhà bình luận chính trị, nhà ngoại giao, nhà phê bình, nhà văn học, nhà giáo dục, chuyên gia ngôn ngữ, nhà tâm linh. Tích cóp làm giàu, phụ nữ làm rạng danh gia đình, thích hợp phát triển trong ngành kinh doanh thương mại.", khacSat: "Bệnh phổi, bệnh vòm họng, bệnh về lưỡi, bệnh đại tràng, bệnh ung thư (vòm miệng, đại tràng, lưỡi), mụn nhọt, uống thuốc độc, ngộ độc, bệnh về đường sinh dục. Thiếu phụ mạo phạm gia chủ, bị tử hình, tàn phế, bị tai nạn xe cộ mà chết." },
    "7-6": { quaiTen: "Trạch Thiên Quải", sinhVuong: "Thích hợp làm quan tòa, luật sư, nhà bình luận chính trị, có tài hùng biện, khéo léo, tiêu diệt thế lực tà ác, bảo vệ pháp luật, luật lệ nghiêm minh. Tiền của vào nhà, thích hợp phát triển trong ngành chế tạo vũ khí. Gia đình hoà thuận, phát cả đinh lẫn tài.", khacSat: "Bệnh phổi, đau đầu, đau nhức xương, bệnh thận, bệnh về tai, bệnh đại tràng, bệnh về đường sinh dục. Tai nạn đổ máu, chém giết, bị thương do dao, cướp giật, mất cắp, mất vợ, phụ nữ gặp tai họa." },
    "7-7": { quaiTen: "Đoài Vi Trạch", sinhVuong: "Vượng cả đinh lẫn tài, chi út giàu có. Con gái trong nhà tài giỏi, khéo léo. Lợi về ngành tư pháp, ngành y, bói toán, đặc biệt nên làm luật sư, quan tòa. Làm giàu nhanh chóng, nên làm kinh doanh, có quý nhân phù trợ.", khacSat: "Bệnh phổi, bệnh vòm họng, bệnh đại tràng, bị cảm, sứt môi, cảm cúm, bệnh về đường hô hấp, bệnh về mũi, bị thương do dao, chứng nhiệt sinh đờm. Cốt nhục tương tàn, chém giết, tai nạn đổ máu, tai nạn xe cộ, trộm cướp, tranh cãi, bịa chuyện đặt điều, mất vợ, tuyệt tự, thiếu phụ nắm quyền, tổn hại đến bé gái, nam nữ dâm loạn. Nếu hình thể núi hoặc dòng nước xấu thì chủ bé gái bị giết hại. Nếu hình thể núi hoặc dòng nước dâm thì chủ thiếu phụ ngoại tình." },
    "7-8": { quaiTen: "Trạch Sơn Hàm", sinhVuong: "Trai tài gái sắc, vợ chồng hoà thuận, lợi về hôn nhân. Của cải dư dật, nên làm ngành y, bói toán, gia sản kếch xù.", khacSat: "Bệnh phổi, bệnh vòm họng, bệnh đại tràng, bệnh dạ dày, đau tay, đau đầu, bệnh tinh thần, bệnh cột sống, đau nhức gân cốt, bệnh kết sỏi, bệnh điên, đau nhức xương. Thiếu nam thiếu nữ sống phóng đãng, vợ chồng xích mích, vợ mạo phạm chồng, bị người âm nhập, mất tiền mất của. Nếu hình thể dòng nước xấu thì chủ tổn hại đến bé trai hoặc chồng. Nếu hình thể núi xấu thì chủ tổn hại đến bé gái. Không có lợi cho người mệnh Đoài." },
    "7-9": { quaiTen: "Trạch Hỏa Cách", sinhVuong: "Thích hợp làm luật sư, quan tòa, nhà nghiên cứu khoa học. Dễ xuất người đẹp, thay đổi diện mạo làm con người mới, quyết tâm sửa chữa sai lầm.", khacSat: "Chủ mắc bệnh vòm họng, bệnh phổi, bệnh đường ruột, bệnh về máu, thổ huyết, bệnh lậu, bệnh lao, bệnh tim, chứng nhiệt, trĩ lậu. Nghiện hút, ngộ độc, hỏa hoạn, chết cháy, bị bỏng, bị thương do vật nổ, mù màu, gặp nguy hiểm khi sinh nở, đào hoa, đam mê tửu sắc. Người âm bị quấy nhiễu, điều tiếng thị phi, mất của hao tài, tổn hại đến bé gái. Nếu hình thể dòng nước xấu thì chủ tổn thương thiếu nữ. Nếu hình thể núi xấu thì chủ tổn thương bé gái. Không có lợi cho người mệnh quẻ Đoài. ### **CÁT HUNG CỦA BÁT BẠCH THỔ TINH VÀ TỔ HỢP CỬU TINH**" },
    "8-1": { quaiTen: "Sơn Thủy Mông", sinhVuong: "Tu thân dưỡng tính, tài cao học rộng. Thích hợp làm họa sĩ, làm giàu nhờ ngành chăn nuôi.", khacSat: "Bệnh thận, sỏi bàng quang, bệnh về mũi, thiếu máu, ung thư máu, bệnh..về tai, sỏi thận. Tổn hại đến trung nam, trong nhà có người đần độn, anh em bất hoà, ngã xuống vực, kiện tụng triền miên, điều tiếng thị phi." },
    "8-2": { quaiTen: "Sơn Địa Bác", sinhVuong: "Cơ nghiệp khá giả, nên làm giàu bằng nghề kinh doanh bất động sản, hoặc xuất nhập khẩu. Mẹ hiền con hiếu thảo, nhân khẩu đông đúc.", khacSat: "Bệnh dạ dày, bệnh vùng bụng, bệnh da liễu, đau ngón tay, bệnh cột sống, phụ nữ mắc bệnh tinh thần, đau nhức gân cốt, dạ dày kết sỏi, thiếu nam cảm điếc, bệnh giun móc, đần độn. Trong nhà có người xuất gia, bị chó cắn, bại hoại gia phong, gia cảnh suy sút." },
    "8-3": { quaiTen: "Sơn Lôi Di", sinhVuong: "Tự lập tự cường, nên phát triển và làm giàu từ các ngành liên quan đến lương thực, hoa cỏ, nhạc cụ và thủ công nghệ. Con cháu trong nhà thông minh.", khacSat: "Bệnh dạ dày, đau ngón tay, bệnh cột sống, đau nhức gân cốt, đau cánh tay, bệnh tinh thần, bệnh kết sỏi, sảy thai. Không có lợi cho người vị thành niên, không có con nối dõi. Anh em không hoà thuận, người cùng một nhà gây gổ với nhau. Không có lợi cho người mệnh Cấn." },
    "8-4": { quaiTen: "Sơn Phong Cổ", sinhVuong: "Lợi cho công việc liên quan đến giấy tờ, phổ biến công việc ở địa phương. Cơ nghiệp khá giả, nên kinh doanh hàng dệt may, tơ tằm.", khacSat: "Đau ngón tay, bệnh phong, bệnh sỏi mật, bệnh ở vú, đau bắp đùi, bệnh cột sống, hen suyễn, bệnh dạ dày, thiếu phụ mắc bệnh tinh thần, thiếu nam mắc bệnh dạ dày, động kinh, bại liệt. Hại chồng khác con, chủ về quả phụ lo liệu việc nhà, tổn hại đến người vị thành niên, dễ bị thú vật cắn." },
    "8-5": { quaiTen: "Không Quẻ", sinhVuong: "Thiếu niên thông minh, trong nhà có người theo nghề khoáng chất, hoặc có người xuất gia.", khacSat: "Bệnh về mũi, đau đầu, bệnh dạ dày, đau ngón tay, bệnh tinh thần, gãy xương, đau nhức gân cốt, bệnh cột sống, bệnh kết sỏi, thiếu nam mắc bệnh thận, đần độn, cảm điếc, đau thần kinh tọa. Khuynh gia bại sản, tổn hại đến con nối dõi, thiếu niên mất mạng." },
    "8-6": { quaiTen: "Sơn Thiên Đại Súc", sinhVuong: "Làm giàu nhờ đất đai, hoặc làm trong ngành tài chính. Cha hiền con hiếu thảo, gia đình vẻ vang.", khacSat: "Bệnh phổi, đau đầu, đau cổ, bệnh đại tràng, đau nhức xương, bệnh dạ dày, suy nhược thần kinh, đau ngón tay, bệnh cột sống, bệnh kết sỏi, sa dạ dày. Thiếu nam bất hiếu với cha, thiếu nam khiến tan của nát nhà, mất vợ, không có con nối dõi." },
    "8-7": { quaiTen: "Sơn Trạch Tổn", sinhVuong: "Nhân khẩu đông đúc, thiếu niên phát đạt sớm, chủ phú quý. Đất đai mở rộng, kinh doanh có lợi, chủ giàu có.", khacSat: "Bệnh phổi, bệnh vòm họng, bệnh đại tràng, bệnh dạ dày, đau ngón tay, bệnh tinh thần, bệnh cột sống, bệnh kết sỏi, bệnh hủi. Vợ chồng bất hoà, bị kẻ gian giết hại, tổn hại đến người vị thành niên, mất của, bị quấy rối tình dục." },
    "8-8": { quaiTen: "Cấn Vi Sơn", sinhVuong: "Phát về đất đai, của cải dư dật, nhân khẩu đông đúc, giàu sang phú quý, sống thọ. Nên kinh doanh hoặc theo nghề nhà giáo, có tài có trí, là nhân viên trung thành, thích hợp với nghề viết lách, không nên làm trong doanh nghiệp như kiểu công xưởng. Nên ngồi thiền, làm thông hai huyệt vị Nhâm và Đốc.", khacSat: "Đau nhức gân cốt, đau xương, bệnh cột sống, dạ dày kết sỏi, chứng liệt dạ dày, chi trên ở nam vị thành niên thường bị dị tật, bệnh dạ dày, thiếu niên cảm điếc, đần độn. Dễ bị chó cắn, thiếu niên sống không tốt, tính tình bảo thủ, nam vị thành niên mất mạng. Nếu hình thể dòng nước xấu thì chủ bé trai mất mạng, hoặc bé trai bị chó dại cắn. Nếu hình thể núi hoặc dòng nước dâm thì chủ đàn ông dâm loạn." },
    "8-9": { quaiTen: "Sơn Hỏa Bí", sinhVuong: "Gặp nhiều may mắn, đất đai nhiều, giàu có. Nên kinh doanh đất đai hoặc đồi rừng. Cuộc sống hôn nhân hạnh phúc, sinh quý tử, lợi cho thiếu nam.", khacSat: "Mắc bệnh về máu, xuất huyết, bệnh tim, huyết áp cao, não xuất huyết, bệnh dạ dày, bệnh về mũi, bệnh đại tràng, bệnh về mắt, mủ máu, chứng viêm, chứng nhiệt, bị bỏng, bị thiêu, trung nữ và thiếu nam mắc bệnh tinh thần, chứng liệt dạ dày, đau mắt hột, chảy máu cam, chi trên xuất huyết. Vợ chồng không hợp nhau. Nếu hình thể dòng nước xấu thì chủ tổn hại đến thiếu nữ. Nếu hình thể núi xấu thì bé trai mất mạng. ### **CÁT HUNG CỦA CỬU TỬ HỎA TINH VÀ TỔ HỢP CỬU TINH**" },
    "9-1": { quaiTen: "Hỏa Thủy Vị Tế", sinhVuong: "Vợ chồng hạnh phúc, đông con nhiều cháu. Của cải dư dật, kinh doanh thuận lợi, chủ phú quý.", khacSat: "Bệnh tim, bệnh thận, bệnh về đường sinh dục, mủ, bệnh về mắt, thần trí mơ hồ. Vợ chồng bất hoà, vợ đoạt quyền chồng, vợ chồng phân ly, đam mê tửu sắc." },
    "9-2": { quaiTen: "Hỏa Địa Tấn", sinhVuong: "Sinh con phú quý, nhân khẩu đông đúc, học rộng hiểu nhiều, nổi tiếng thiên hạ, công việc thuận lợi, thăng quan tiến chức. Hợp với nghề làm gốm, kinh doanh vất vả, làm ăn hợp pháp.", khacSat: "Bệnh dạ dày, bệnh về máu, xuất huyết dạ dày, viêm dạ dày, viêm ruột thừa, bệnh về mắt, bệnh tim, khó sinh, viêm phúc mạc. Giết người, tai nạn đổ máu, mạo phạm cấp trên, không biết điều. Chồng bảo thủ đần độn, hao tốn nhân đinh, gia cảnh nghèo khó, đam mê tửu sắc, gặp kiếp đào hoa." },
    "9-3": { quaiTen: "Hỏa Lôi Phệ Hạp", sinhVuong: "Sinh con thông minh xinh đẹp, đường thăng quan tiến chức thuận lợi, tài lộc thường vào nhà. Trung nữ phúc thọ song toàn, con dâu thứ mang thai con trai. Thanh Long vào nhà, Mộc Hỏa tương thông.", khacSat: "Bệnh gan, đau chân, bệnh về mắt, bệnh về máu, ung thư máu, chứng viêm, bệnh dịch, bị thiêu chết, bị bỏng, khó sinh, bệnh tim. Bị vật nổ làm chân bị thương, tổn hại nhân đinh, mất của, nam trộm cắp nữ làm gái nhà hàng, phải ngồi tù." },
    "9-4": { quaiTen: "Hỏa Phong Đỉnh", sinhVuong: "Chi trưởng sinh quý tử, thông minh xinh đẹp, có trình độ học vấn cao, thành tích nổi bật, thăng quan tiến chức, nên làm nhân viên công chức. Phụ nữ làm rạng danh gia đình, tài lộc dồi dào, gia đình hạnh phúc.", khacSat: "Chứng viêm, viêm phế quản, bệnh về mắt, bệnh về ống mật, viêm tuyến vú, bệnh về máu, đau bắp đùi, bệnh phong, hao tổn sinh khí, bệnh tim, mất máu, bệnh đại tràng, nhiễm khuẩn, đau đầu chóng mặt, hủy hoại dung nhan. Tai nạn đổ máu, bị thương do dao, thất cơ tự tử, bị thiêu chết, mất của, hao tổn nhân đinh, trong nhà có kẻ sống lang thang, phụ nữ bất hoà, gia trạch không yên." },
    "9-5": { quaiTen: "Không Quẻ", sinhVuong: "Sinh quý tử, nhân khẩu đông đúc. Tài lộc dồi dào, đất đai rộng rãi. Trong nhà có người làm quan lớn. Nên theo ngành quân sự, có tiếng và nghề làm gốm.", khacSat: "Bệnh tim, bệnh về huyết quản, ung thư máu, bệnh đại tràng, mù màu, khó sinh, vô sinh, sảy thai, nhiễm khuẩn, chứng viêm, mụn nhọt, viêm dạ dày, xuất huyết dạ dày, loét tá tràng, bệnh da liễu, bị bỏng, ung thư đại tràng, tàn tật, gầy gò, chết yểu. Kiện tụng, tử hình, dâm loạn, mất của." },
    "9-6": { quaiTen: "Hỏa Thiên Đại Hữu", sinhVuong: "Học rộng hiểu nhiều, vui tươi hồ hởi, tinh thần phấn chấn, giàu có, sống thọ.", khacSat: "Bệnh phổi, bệnh về máu, chứng viêm, xuất huyết, bệnh tim, não xuất huyết, bệnh về tuyến giáp, đau cổ, đau nhức xương, đau đầu, bệnh đại tràng, bệnh nhiệt, bị thiêu chết, bị bỏng, sảy thai, vô sinh, khó sinh, ung thư máu, xuất huyết não. Chết bất ngờ, con dâu xấu nết, phụ nữ ngang tàng, con cháu bất hiếu, tổn hại đến người già, gây gổ chém giết lẫn nhau, tự sát, nhảy xuống giếng tự vẫn." },
    "9-7": { quaiTen: "Hỏa Trạch Khuê", sinhVuong: "Lấy người khác họ, xinh đẹp yêu kiều. Thích hợp làm chuyên gia chế tạo vũ khí, luật sư, quan tòa, là người giữ gìn chân lý.", khacSat: "Bệnh phổi, bệnh vòm họng, bệnh đại tràng, bệnh về máu, bệnh tim, chứng viêm, xuất huyết, mất máu, nghiện hút, ngộ độc, mù màu, bệnh về mắt, vô sinh, ung thư vòm miệng, thổ huyết, ung thư phổi. Hỏa hoạn, bị bỏng, vật nổ làm bị thương. Đam mê tửu sắc, kiện tụng, tai họa bất ngờ, anh em bất hoà, cuộc sống gia đình không được yên ổn, bại hoại gia phong, phóng đãng dâm dật." },
    "9-8": { quaiTen: "Hỏa Sơn Lữ", sinhVuong: "Của cải dư dật, nhân khẩu đông đúc. Trung nam trung nữ giàu có, sinh quý tử, thiếu nam công thành danh toại. Phát triển thuận lợi về ngành nông nghiệp, kinh doanh thương mại.", khacSat: "Bệnh về máu, xuất huyết, bệnh tim, huyết áp cao, não xuất huyết, bệnh dạ dày, bệnh về mũi, đau mắt, bệnh đại tràng, bị bỏng, bị thiêu, tự thiêu, đần độn, cảm điếc. Người vị thành niên bị mất mạng, phụ nữ thô bạo, trẻ em bị thiểu năng tâm thần." },
    "9-9": { quaiTen: "Ly Vi Hỏa", sinhVuong: "Cơ nghiệp khá giả, giàu sang phú quý. Thích hợp với nghề nấu ăn, luyện kim, mỹ phẩm, thời trang. Gia cảnh khá giả, nhưng dễ giàu cũng dễ suy bại.", khacSat: "Bệnh về mắt, thần trí mơ màng, bệnh về hệ thống tuần hoàn máu, bệnh về máu, mất máu, xuất huyết, bệnh tim, huyết áp cao, chứng nhiệt, chứng viêm, say nắng, viêm phổi, viêm đại tràng, khó sinh, sảy thai, vô sinh. Hỏa hoạn, tai nạn đổ máu, chết thảm, tự sát, hao tổn nhân đinh, mất của, giết người, kiện tụng, tử hình, âm thịnh dương suy, phụ nữ lo liệu việc nhà, không có lợi cho người vị thành niên. Nếu hình thể núi hoặc dòng nước xấu thì chủ thiếu phụ mất mạng. Nếu hình thể núi hoặc dòng nước dâm thì chủ thiếu nữ dâm loạn." },
};
// Tra tổ hợp theo ĐÚNG thứ tự (huongTinh, sonTinh) — không phải (sonTinh, huongTinh).
window.xetToHopSonHuong = function (huongTinh, sonTinh) {
    return window.TO_HOP_SON_HUONG[huongTinh + "-" + sonTinh] || null;
};

// ====================================================================
// "TEST" — HÀ-LẠC LUẬN (mục thử nghiệm riêng cho tab Nội Khí, KHÔNG đụng tới Luận Chân Khí Tiên
// Thiên cũ). Phương pháp: mọi Ngũ hành (Hướng, Tọa, Vận) đều lấy theo ĐÚNG Hậu Thiên/Lạc Thư như
// toàn bộ app đang dùng (HANH_CUA_CUNG, HANH_CUA_SAO) — số Hà Đồ (vd "1,6") chỉ là NHÃN ĐI KÈM để
// tra cứu Loại Tượng Hà Đồ, không phải một bước quy đổi ngũ hành riêng.
// ====================================================================

// ===== Cặp số Hà Đồ ứng với mỗi Ngũ hành + Loại Tượng (Sinh vượng/Khắc sát) — nguồn: Hà Đồ Lạc
// Thư.md do Ka cung cấp. =====
window.HA_DO_LOAI_TUONG = {
    "Thủy": { soHaDo: "1, 6", sinhVuong: "Văn nhân, đứng đầu bảng vàng, thông minh tài trí.", khacSat: "Dâm loạn, quả phụ, con cái chơi bời lêu lổng, lũ lụt, phiêu bạt." },
    "Hỏa":  { soHaDo: "2, 7", sinhVuong: "Giàu có, nhiều của cải, thường gặp điều may mắn bất ngờ, nhiều con gái.", khacSat: "Thổ huyết, sảy thai, khó sinh, chết yểu, tai nạn bất ngờ." },
    "Mộc":  { soHaDo: "3, 8", sinhVuong: "Có tài văn chương, phát khoa danh, đường thăng quan tiến chức thuận lợi, nhiều con trai.", khacSat: "Chết trẻ, tuyệt tự." },
    "Kim":  { soHaDo: "4, 9", sinhVuong: "Giàu có, hiểu nghĩa, nhiều con trai.", khacSat: "Gặp nạn binh đao, cô quả, thất cơ, tự sát." },
    "Thổ":  { soHaDo: "5, 10", sinhVuong: "Phát rất nhanh, đông con nhiều cháu, được hưởng lộc trời cho.", khacSat: "Mắc dịch bệnh, quả phụ, chết chóc." }
};

// ===== Mệnh Quái (Đông Tứ Mệnh / Tây Tứ Mệnh) từ năm sinh Dương lịch + giới tính =====
// Công thức chuẩn phổ biến trong Bát Trạch — CẦN KA XÁC NHẬN LẠI vì đây là công thức tiêu chuẩn
// tôi áp dụng, không phải nguyên văn Ka cung cấp.
window.tinhMenhQuai = function (namSinh, gioiTinh) {
    let hai_so_cuoi = namSinh % 100;
    let tong = Math.floor(hai_so_cuoi / 10) + (hai_so_cuoi % 10);
    while (tong > 9) tong = Math.floor(tong / 10) + (tong % 10);
    let quaiSo;
    let sauNam2000 = namSinh >= 2000;
    if (gioiTinh === "nam") {
        quaiSo = sauNam2000 ? (9 - tong) : (10 - tong);
        while (quaiSo <= 0) quaiSo += 9;
        while (quaiSo > 9) quaiSo -= 9;
        if (quaiSo === 5) quaiSo = 2; // Nam Ngũ Hoàng ký Khôn
    } else {
        quaiSo = sauNam2000 ? (6 + tong) : (5 + tong);
        while (quaiSo > 9) quaiSo -= 9;
        if (quaiSo === 5) quaiSo = 8; // Nữ Ngũ Hoàng ký Cấn
    }
    const CUNG_THEO_QUAI = { 1: "Khảm", 2: "Khôn", 3: "Chấn", 4: "Tốn", 6: "Càn", 7: "Đoài", 8: "Cấn", 9: "Ly" };
    const DONG_TAY = { "Khảm": "Đông Tứ Mệnh", "Chấn": "Đông Tứ Mệnh", "Tốn": "Đông Tứ Mệnh", "Ly": "Đông Tứ Mệnh",
                        "Khôn": "Tây Tứ Mệnh", "Càn": "Tây Tứ Mệnh", "Đoài": "Tây Tứ Mệnh", "Cấn": "Tây Tứ Mệnh" };
    let cung = CUNG_THEO_QUAI[quaiSo];
    return { quaiSo, cung, hanh: window.HANH_CUA_CUNG[cung], nhom: DONG_TAY[cung] };
};
